In [3]:
# Требуется создать вектор как строку и как столбец
import numpy as np 

vector_row = np.array([1,2,3])
vector_column = np.array([[1],[2],[3]])

array([1, 2, 3])

In [4]:
#Требуется создать матрицу
matrix = np.array([[1,2],[1,2],[1,2]])

array([[1, 2],
       [1, 2],
       [1, 2]])

In [8]:
#Имеются данные с очень малым количеством ненулевых значений, которые требуется эффективно представить.
from scipy import sparse
matrix = np.array([[0,0],[0,1],[3,0]])
print(matrix, "\n")

# Создать сжатую разреженную матрицу-строку (CSR-матрицу)
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

[[0 0]
 [0 1]
 [3 0]] 

  (1, 1)	1
  (2, 0)	3
