In [2]:
# Требуется создать вектор как строку и как столбец
import numpy as np 

vector_row = np.array([1,2,3])
vector_column = np.array([[1],[2],[3]])

In [4]:
#Требуется создать матрицу
matrix = np.array([[1,2],[1,2],[1,2]])

array([[1, 2],
       [1, 2],
       [1, 2]])

In [8]:
#Имеются данные с очень малым количеством ненулевых значений, которые требуется эффективно представить.
from scipy import sparse
matrix = np.array([[0,0],[0,1],[3,0]])
print(matrix, "\n")

# Создать сжатую разреженную матрицу-строку (CSR-матрицу)
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

[[0 0]
 [0 1]
 [3 0]] 

  (1, 1)	1
  (2, 0)	3


In [4]:
# Требуется выбрать один или несколько эллементов в векторе или матрице
vector = np.array([1,2,3,4,5,6])

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(vector[0])
print(matrix[0,0])
#Помимо всего прочего к эллементам np n-мерных векторов мы можем обращаться срезами как и к эллементам строк

1
1


In [8]:
#Требуется описать форму, размер и размерность матрицы
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

#Колличество строк и столбцов
matrix.shape

#Размер матрицы - колличество эллементов(строки*столбцы)
matrix.size

#Колличество размерностей - размерность пространства
matrix.ndim

2

In [9]:
#Требуется примениь некоторую функцию к некоторым эллементам массива
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

add_100 = lambda i: i+100

#Создание векторизированной функции
vectorsized_add_100 = np.vectorize(add_100)

vectorsized_add_100(matrix)

#Класс NumPy vectorize конвертирует обычную функцию в функцию, которая может
#применяться ко всем элементам массива или части массива. Стоит отметить,
#что vectorize по существу представляет собой цикл for над элементами и не увеличивает
#производительность.

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [10]:
#Нахождение мнимального и максимального значения в массивах

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.max(matrix)
np.min(matrix)

1

In [12]:
#Трбуется вычеслить некоторые описательные статистичские показатели о массиве

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

#Среднее значение
np.mean(matrix)

#Дисперсия
np.var(matrix)

#Стандартное отклонение
np.std(matrix)

2.581988897471611

In [13]:
#Реформирование массивов. Требуется изменить форму маива без изенения значений эллементов.

matrix = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [15]:
#Транспонирование вектора в матрицу

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [20]:
#Преобразование матрицы в одноерный массив
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

#Сгладить матрицу
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#Нахождение ранга матрицы

matrix = np.array([[1,1,1],[1,1,10],[1,1,15]])

np.linalg.matrix_rank(matrix)

2

In [22]:
#Требуется узнать определитель матрицы

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.linalg.det(matrix)

0.0

In [25]:
#Требуется получить эллементы гавной диагонали матрицы

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

matrix.diagonal()
matrix.diagonal(offset=1)
matrix.diagonal(offset=-2)

array([7])

In [26]:
#Требуется вычеслить след матрицы

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

matrix.trace()

#След матрицы - есть сумма эллементов главной диагонали и часто используется за кадром в эллементах ML.

15

In [28]:
# Требуется найти собственные значеия и собственные вектора матрицы

matrix = np.array([[1,-1,3],[1,1,6],[3,8,9]])

#Вычеслить собственные значения и собственные вектора
eigenvalues, eigenvectors = np.linalg.eig(matrix)

#Собвственные значения
eigenvalues

#Собственные вектора
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

In [29]:
#Вычисление скалярного произведения двух векторов

vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

np.dot(vector_a,vector_b)

32

In [31]:
#Сложение и вычитание матриц

matrix_a = np.array([[1,1,1],[1,1,1],[1,1,2]])
matrix_b = np.array([[1,3,1],[1,3,1],[1,3,0]])

np.add(matrix_a, matrix_b)
np.subtract(matrix_a, matrix_b)   

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2,  2]])

In [32]:
#Умножение матриц

matrix_a = np.array([[1,1],[1,2]])
matrix_b = np.array([[1,3],[1,2]])

np.dot(matrix_a,matrix_b)

array([[2, 5],
       [3, 7]])

In [33]:
#Обращение матрицы

matrix = np.array([[1,4],[2,5]])

#Вычислить обратную иатрицу
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [34]:
#Требуется сгенерровать псевдослучайные значения в матрицу

#Создать начальное значение для генераора случайных чисел
np.random.seed(0)

#Сгенерировть три случайных вещественных числа между 0.0 и 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])